# Generated by Django 4.1.5 on 2023-01-10 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=20)),
                ('remote', models.BooleanField()),
                ('hybrid', models.BooleanField()),
                ('on_site', models.BooleanField()),
                ('application_date', models.DateField()),
                ('follow_up_date', models.DateField()),
                ('connections', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
